# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: h-self-hosted
  vmImage: ubuntu-latest
  
variables:
  JAVA_HOME: '/usr/lib/jvm/java-17-openjdk-amd64'
  
steps:
- script: printenv | grep JAVA_HOME
  displayName: 'Print JAVA_HOMEs'
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'  # Path to your Gradle wrapper
    tasks: 'clean build'  # Replace with the tasks you want to run
    options: '-Xmx3072m' 
    jdkArchitectureOption: 'x64'
