# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: h-self-hosted
  # vmImage: ubuntu-latest # Azure-hosted agent 사용 시
  
variables:
  JAVA_HOME: '/usr/lib/jvm/java-17-openjdk-amd64'
  
steps:
- checkout: self  # 코드 가져오기
  
- script: ./gradlew clean build  # Gradle Wrapper를 사용하여 빌드 실행
  displayName: 'Run Gradle Build'
