# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: h-self-hosted
  # vmImage: ubuntu-latest # Azure-hosted agent 사용 시
  
variables:
  JAVA_HOME: '/usr/lib/jvm/java-17-openjdk-amd64'

stages:
- stage: Vault
  displayName: Vault
  jobs:
  - job: Vault
    displayName: test vault values
    #pool:
    #  vmImage: ubuntu-latest
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'keyvault service'  # Azure Subscription 연결명
        KeyVaultName: 'key-ssh-h-lab'  # Azure Key Vault 이름
        SecretsFilter: '*'  # 가져올 비밀을 선택합니다. *: 전체
        UseManagedIdentity: true
        UserAssignedIdentity: '/subscriptions/f32b0b12-1781-49a3-a03d-02a5338f1f60/resourcegroups/rg-h-cicd-lab/providers/Microsoft.ManagedIdentity/userAssignedIdentities/devops-identity'
    - displayName: 'Display secret'
      script: |
        echo "Secret int Value : $(int-ssh-key)"
        echo "Secret pipeline Value : $(pipeline-test)"


